// (c) 2018 Arnold Noronha <arnold@tdrhq.com>

package com.tdrhq.eyepatch.dexmagic;

import android.util.Log;
import com.tdrhq.eyepatch.util.Checks;

/**
 * All methods generated by EyePatchClassBuilder call into the
 * StaticInvocationHandler via invokeStatic, which then delegates to
 * the global sHandler. This model minimizes the amount of dalvik
 * bytecode we need to generate manually.
 */
public abstract class StaticInvocationHandler {

    private static StaticInvocationHandlerInterface DEFAULT_HANDLER = new DelegatingInvocationHandler();

    private static StaticInvocationHandlerInterface sHandler = DEFAULT_HANDLER;

    public static void setDefaultHandler() {
        sHandler = DEFAULT_HANDLER;
    }

    public static void setHandler(StaticInvocationHandlerInterface handler) {
        sHandler = Checks.notNull(handler);
    }

    public StaticInvocationHandler() {
    }

    public static Object invokeStatic(
            Class klass,
            Object instance,
            String method,
            Class[] argTypes,
            Object[] args) {
        Invocation invocation = new Invocation(klass, instance, method, argTypes, args);
        if (sHandler != null) {
            return sHandler.handleInvocation(invocation);
        }

        return null;
    }
}
